// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.Routers.Main = (function(_super) {

    __extends(Main, _super);

    function Main() {
      this.urlShowList = __bind(this.urlShowList, this);

      this.urlShowIndex = __bind(this.urlShowIndex, this);
      return Main.__super__.constructor.apply(this, arguments);
    }

    Main.prototype.routes = {
      "": "routeIndex",
      "list/:slug": "routeList"
    };

    Main.prototype.initialize = function() {
      App.Mediator.bind("listSelected", this.urlShowList);
      return App.Mediator.bind("listDeselected", this.urlShowIndex);
    };

    Main.prototype.routeIndex = function() {};

    Main.prototype.routeList = function(slug) {
      var list;
      if (list = App.Models.Lists.bySlug(slug)) {
        return list.setSelected();
      } else {
        return _.each(App.Models.Lists.selected(), function(list) {
          return list.set({
            "selected": false
          });
        });
      }
    };

    Main.prototype.urlShowIndex = function() {
      document.title = "All Lists - InterMine MyMine";
      if (App.Models.Lists.selected.length === 0) {
        return this.navigate("");
      }
    };

    Main.prototype.urlShowList = function(slug) {
      var name;
      name = App.Models.Lists.bySlug(slug).get("name");
      document.title = "" + name + " - InterMine MyMine";
      return this.navigate("list/" + slug);
    };

    return Main;

  })(Backbone.Router);

}).call(this);
