// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.Views.FolderCollectionView = (function(_super) {

    __extends(FolderCollectionView, _super);

    function FolderCollectionView() {
      return FolderCollectionView.__super__.constructor.apply(this, arguments);
    }

    FolderCollectionView.prototype.el = "div#folder";

    return FolderCollectionView;

  })(Backbone.View);

}).call(this);
