// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.Views.FolderView = (function(_super) {

    __extends(FolderView, _super);

    function FolderView() {
      return FolderView.__super__.constructor.apply(this, arguments);
    }

    FolderView.prototype.tagName = "table";

    FolderView.prototype.template = function(model) {
      return FolderView.__super__.template.call(this, model, "js/templates/_folder.html");
    };

    return FolderView;

  })(Backbone.View);

}).call(this);
