// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.Views.SidebarListSearchView = (function(_super) {

    __extends(SidebarListSearchView, _super);

    function SidebarListSearchView() {
      this.filter = __bind(this.filter, this);
      return SidebarListSearchView.__super__.constructor.apply(this, arguments);
    }

    SidebarListSearchView.prototype.el = "input#list-search";

    SidebarListSearchView.prototype.events = {
      keyup: "filter"
    };

    SidebarListSearchView.prototype.filter = function() {
      return App.Mediator.trigger("filterLists", $(this.el).attr("value"));
    };

    return SidebarListSearchView;

  })(Backbone.View);

}).call(this);
